services:
  - type: web
    name: tooth-and-nail-backend
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm ci && npm run build && npx medusa db:migrate
    startCommand: npm run start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: COOKIE_SECRET
        generateValue: true
      - key: STORE_CORS
        value: https://toothandnail-v2-7aft.vercel.app
      - key: ADMIN_CORS
        value: https://tooth-and-nail-backend.onrender.com
      - key: AUTH_CORS
        value: https://tooth-and-nail-backend.onrender.com,https://toothandnail-v2-7aft.vercel.app
      - key: MEDUSA_BACKEND_URL
        value: https://tooth-and-nail-backend.onrender.com